---
- name: Crea la cartella di lavoro per le VM
  ansible.builtin.file:
    path: "{{ vagrant_workdir }}"
    state: directory
    mode: "0755"

- name: Crea la cartella per l'inventory
  ansible.builtin.file:
    path: "{{ vagrant_inventory_file | dirname }}"
    state: directory
    mode: "0755"

- name: Crea e avvia le VM
  community.vagrant.vagrant:
    workdir: "{{ vagrant_workdir }}"
    provider_name: "{{ vagrant_provider }}"
    default_box: "{{ vagrant_box }}"
    instances: "{{ vms }}"

- name: Scrivi l'inventario
  ansible.builtin.template:
    src: inventory.j2
    dest: "{{ vagrant_inventory_file }}"
    mode: "0644"

- name: Ricarica l'inventory appena generato
  ansible.builtin.meta: refresh_inventory
